baseURL: 'https://moodletoolguide.net/'
languageCode: en-us

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage: en

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: true

disableKinds:
- taxonomy
- taxonomyTerm

markup:
  goldmark:
    renderer:
      hardWraps: true

params:
  author: Nicolas Martignoni
  githubUsername: 'martignoni'
  accent: '#f98012'
  showBorder: true
  backgroundColor: white
  matomoAnalytics:
    siteid: 4
    matomoroot: "stats.martignoni.net" # Do not add slashes
  menu:
    icon:
      - url: 'mailto:nicolas@martignoni.net'
        name: envelope-o
        weight: 1
      - url: 'https://github.com/martignoni/moodle-tool-guide'
        name: github
        weight: 2
  js: 'js/custom.js'

languages:
  en:
    languageName: English
    title: Moodle Tool Guide
    slogan: Moodle Tool Guide for teachers and educators
    description: 'Moodle Tool Guide: A Quick Reference Guide for teachers and educators to use Moodle version 3 and later.'
    contentDir: content/en
    date_format: January 2, 2006
    copyright: 'Provided by [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – The website __[moodletoolguide.net](https://moodletoolguide.net)__ is licensed under a [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) License.


      An idea of [Joyce Seitzinger](https://twitter.com/catspyjamasnz) of [Eastern Institute of Technology](https://www.eit.ac.nz/) (NZ). Adapted by [Nicolas Martignoni](https://blog.martignoni.net/a-propos/), based on work by [Gavin Henrick](https://twitter.com/ghenrick).'
    weight: 1
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: About
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  fr:
    languageName: Français
    title: Guide des outils Moodle
    slogan: Guide des outils Moodle pour enseignant·es et formateur·trices
    description: "Guide des outils Moodle : un aide-mémoire pour l'utilisation de Moodle version 3 et ultérieures, destiné aux enseignantes et enseignants et aux formatrices et formateurs."
    contentDir: content/fr
    date_format: 2 January 2006
    copyright: 'Offert par [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Le site web __[moodletoolguide.net](https://moodletoolguide.net)__ est publié sous licence [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).'
    weight: 2
    menu:
      main:
        - url: /
          name: Accueil
          weight: 1
        - url: /about/
          name: À propos
          weight: 1
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  it:
    languageName: Italiano
    title: Guida agli strumenti Moodle
    slogan: Guida agli strumenti Moodle per insegnanti e formatori
    description: "Guida agli strumenti Moodle: un promemoria per l'utilizzo di Moodle versione 3 e successive, destinato a insegnanti e formatori."
    contentDir: content/it
    date_format: 2 January 2006
    copyright: 'Offerto da [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Il sito web __[moodletoolguide.net](https://moodletoolguide.net)__ è pubblicato sotto licenza [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).'
    weight: 3
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: Saperne di più
          weight: 1
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  de:
    languageName: Deutsch
    title: Moodle Werzeuge für Lehrpersonen
    slogan: Moodle-Werkzeuge für Lehrpersonen und Trainer
    description: 'Moodle-Werkzeuge für Lehrpersonen: Eine Kurzanleitung für Lehrpersonen und Trainer zur Verwendung von Moodle Version 3 und neuer.'
    contentDir: content/de
    date_format: 2. January 2006
    copyright: 'Angeboten von [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Die Website __[moodletoolguide.net](https://moodletoolguide.net)__ ist lizenziert unter einer [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) Lizenz.'
    weight: 4
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: Über
          weight: 1
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2
