baseURL: 'https://moodletoolguide.net/'
languageCode: en-us

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage: en

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: true

# Enable robots.txt generation
enableRobotsTXT: true

disableKinds:
- taxonomy
- taxonomyTerm

markup:
  goldmark:
    renderer:
      hardWraps: true

params:
  author: Nicolas Martignoni
  githubUsername: 'martignoni'
  accent: '#f98012'
  showBorder: true
  backgroundColor: white
  matomoAnalytics:
    siteid: 4
    matomoroot: "stats.martignoni.net" # Do not add slashes
  menu:
    icon:
      - url: 'mailto:nicolas@martignoni.net'
        name: envelope-o
        weight: 1
      - url: 'https://github.com/martignoni/moodle-tool-guide'
        name: github
        weight: 2
  js: 'js/custom.js'

languages:
  en:
    languageName: English
    weight: 1
    title: Moodle Tool Guide
    slogan: Moodle Tool Guide for teachers and educators
    description: 'Moodle Tool Guide: A Quick Reference Guide for teachers and educators to use Moodle version 3 and later.'
    keywords:
    - Moodle
    - Moodle Tools
    - Moodle Tools Guide
    - Moodle Tool Guide
    - Moodle Tool Guide for teachers
    - Moodle Tools for teachers
    - Moodle Guide
    - Moodle Guide for teachers
    - Moodle Guide for instructors
    - Moodle Guide for trainers
    contentDir: content/en
    date_format: January 2, 2006
    copyright: 'Provided by [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – The website __[moodletoolguide.net](https://moodletoolguide.net)__ is licensed under a [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) License.


      An idea of [Joyce Seitzinger](https://twitter.com/catspyjamasnz) of [Eastern Institute of Technology](https://www.eit.ac.nz/) (NZ). Adapted by [Nicolas Martignoni](https://blog.martignoni.net/a-propos/), based on work by [Gavin Henrick](https://twitter.com/ghenrick).'
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: About
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  fr:
    languageName: Français
    weight: 2
    title: Guide des outils Moodle
    slogan: Guide des outils Moodle pour enseignant·es et formateur·trices
    description: "Guide des outils Moodle : un aide-mémoire pour l'utilisation de Moodle version 3 et ultérieures, destiné aux enseignantes et enseignants et aux formatrices et formateurs."
    keywords:
    - Moodle
    - Outils Moodle
    - Guide des outils Moodle
    - Outils Moodle pour enseignants
    - Guide des outils Moodle pour enseignants
    - Outils Moodle pour formateurs
    - Guide Moodle
    - Guide Moodle pour enseignants
    - Guide Moodle pour formateurs
    contentDir: content/fr
    date_format: 2 January 2006
    copyright: "Offert par [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Le site web __[moodletoolguide.net](https://moodletoolguide.net)__ est publié sous licence [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).


      Une idée de [Joyce Seitzinger](https://twitter.com/catspyjamasnz) de l'[Eastern Institute of Technology](https://www.eit.ac.nz/) (NZ), traduite en français et adaptée par [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) avec des contributions de Fabien Balli."
    menu:
      main:
        - url: /
          name: Accueil
          weight: 1
        - url: /about/
          name: À propos
          weight: 1
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  it:
    languageName: Italiano
    weight: 3
    title: Guida agli strumenti Moodle
    slogan: Guida agli strumenti Moodle per insegnanti e formatori
    description: "Guida agli strumenti Moodle: un promemoria per l'utilizzo di Moodle versione 3 e successive, destinato a insegnanti e formatori."
    keywords:
    - Moodle
    - Moodle Tools
    - Moodle Tools Guide
    - Moodle Tool Guide
    - Moodle Tool Guide for teachers
    - Moodle Tools for teachers
    - Moodle Guide
    - Moodle Guide for teachers
    - Moodle Guide for instructors
    - Moodle Guide for trainers
    contentDir: content/it
    date_format: 2 January 2006
    copyright: "Offerto da [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Il sito web __[moodletoolguide.net](https://moodletoolguide.net)__ è pubblicato sotto licenza [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).


      Un'idea di [Joyce Seitzinger](https://twitter.com/catspyjamasnz) del'[Eastern Institute of Technology](https://www.eit.ac.nz/) (NZ), aggiornata da [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) e tradotta in italiano da [Luca Confortola](https://twitter.com/ConfortolaLuca)."
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: Saperne di più
          weight: 1
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  de:
    languageName: Deutsch
    weight: 4
    title: Moodle-Werkzeuge für Lehrpersonen
    slogan: Moodle-Werkzeuge für Lehrpersonen und Trainer
    description: 'Moodle-Werkzeuge für Lehrpersonen: Eine Kurzanleitung für Lehrpersonen und Trainer zur Verwendung von Moodle Version 3 und neuer.'
    keywords:
    - Moodle
    - Moodle Tools
    - Moodle Tools Guide
    - Moodle Tool Guide
    - Moodle Tool Guide for teachers
    - Moodle Tools for teachers
    - Moodle Guide
    - Moodle Guide for teachers
    - Moodle Guide for instructors
    - Moodle Guide for trainers
    - Moodle-Werkzeuge für Lehrpersonen
    - Moodle-Werkzeuge für Trainer
    - Moodle-Werkzeuge für Lehrpersonen und Trainer
    contentDir: content/de
    date_format: 2. January 2006
    copyright: 'Angeboten von [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Die Website __[moodletoolguide.net](https://moodletoolguide.net)__ ist lizenziert unter einer [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) Lizenz.


      Eine Idee von [Joyce Seitzinger](https://twitter.com/catspyjamasnz) von [Eastern Institute of Technology](https://www.eit.ac.nz/) (NZ), auf deutsch von [Ralf Hilgenstock](https://twitter.com/ralfh), Susanne Gebauer und Gerald Hartwig übertragt. Angepasst von [Nicolas Martignoni](https://blog.martignoni.net/a-propos/).'
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: Über
          weight: 1
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  es:
    languageName: Español
    weight: 5
    title: Guía de las herramientas de Moodle
    slogan: Guía de las herramientas de Moodle para docentes y formadores
    description: ""
    keywords:
    - Moodle
    - herramientas de Moodle
    - Guía de las herramientas de Moodle
    - Herramientas de Moodle para docentes
    - Herramientas de Moodle para formadores
    - Guía de las herramientas de Moodle para docentes
    - Guía de las herramientas de Moodle para formadores
    - Guía de Moodle
    - Guía de Moodle para docentes
    - Guía de Moodle para formadores
    contentDir: content/pt-pt
    date_format: 2 January 2006
    copyright: "Ofertado por [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – El sitio web __[moodletoolguide.net](https://moodletoolguide.net)__ tiene una licencia [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).


      Una idea de [Joyce Seitzinger](https://twitter.com/catspyjamasnz) de la [Eastern Institute of Technology](https://www.eit.ac.nz/) (NZ), adaptado por [Nicolas Martignoni](https://blog.martignoni.net/a-propos/), Traducido y adaptado al castellano por [Ramón Ovelar](https://moodle.org/user/profile.php?id=13611)."
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: About
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  eu:
    languageName: Euskara
    weight: 6
    title: Moodleko Tresnen Gida
    slogan: Moodleko Tresnen Gida irakasle eta hezitzaileentzat
    description: 'Moodleko Tresnen Gida: 3 edo bertsio berriago bat erabiltzeko irakasle, hezitzaile eta trebatzaileentzat diseinatutako erreferentziazko taula da.'
    keywords:
    - Moodle
    - Moodleko Tresnak
    - Moodleko Tresnen Gida
    - Moodleko Tresnen Gida
    - Moodleko Tresnen Gida irakasleentzat
    - Moodleko Tresnak irakasleentzat
    - Moodleko Gida
    - Moodleko Gida irakasleentzat
    - Moodleko Gida hezitzaileentzat
    - Moodleko Gida trebatzaileentzat
    contentDir: content/eu
    date_format: 2006 January 2
    copyright: '[Nicolas Martignoni](https://blog.martignoni.net/a-propos/)-ek egina – __[moodletoolguide.net](https://moodletoolguide.net)__ webgunea [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/) lizentziapean argitaratu da.


      Tresna hau [Eastern Institute of Technology](https://www.eit.ac.nz/)-ko (Zeelanda Berria) [Joyce Seitzinger](https://twitter.com/catspyjamasnz)-en ideia izan zen, 2020ko maiatzean Moodle 3.x-erako [Nicolas Martignoni][nm]-ek egokitua eta [Iñigo Zendegi](https://moodle.org/user/profile.php?id=709961)k euskaratua.'
    menu:
      main:
        - url: /
          name: Hasiera
          weight: 1
        - url: /about/
          name: Honi buruz
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  pt-br:
    languageName: Português do Brasil
    weight: 7
    title: Guia de Ferramentas Moodle
    slogan: Guia de Ferramentas Moodle para Professores e Educadores
    description: "Guia de Ferramentas Moodle: Um Guia de Referência Rápida para professores e educadores usarem o Moodle versão 3 e posterior."
    keywords:
    - Moodle
    - Ferramentas Moodle
    - Guia de Ferramentas Moodle
    - Ferramentas Moodle para Professores
    - Ferramentas Moodle para Educadores
    - Guia de Ferramentas Moodle para Professores
    - Guia de Ferramentas Moodle para Educadores
    - Guia Moodle para Professores
    - Guia Moodle para Educadores
    contentDir: content/pt-br
    date_format: 2 January 2006
    copyright: "Disponibilizado por [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Website __[moodletoolguide.net](https://moodletoolguide.net)__ Licença [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).


      Baseado na ideia de [Joyce Seitzinger](https://twitter.com/catspyjamasnz) do [Eastern Institute of Technology](https://www.eit.ac.nz/) (NZ), adaptado por [Nicolas Martignoni](https://blog.martignoni.net/a-propos/), traduzido e adaptado para Português do Brasil por [Gilvan Marques](https://twitter.com/gmarques)."
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: Sobre
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2

  pt-pt:
    languageName: Português
    weight: 8
    title: Guia de Ferramentas do Moodle
    slogan: Guia de ferramentas do Moodle para professores e formadores
    description: "Guia de Ferramentas do Moodle: um guia rápido sobre a utilização do Moodle, versão 3 e posteriores, destinado a professores e formadores."
    keywords:
    - Moodle
    - Ferramentas do Moodle
    - Guia de Ferramentas do Moodle
    - Ferramentas Moodle para professores
    - Guia de ferramentas do Moodle para educadores
    - Ferramentas Moodle para formadores
    - Guia do Moodle
    - Guia Moodle para educadores
    - Guia Moodle para formadores
    contentDir: content/pt-pt
    date_format: 2 January 2006
    copyright: "Disponibilizado por [Nicolas Martignoni](https://blog.martignoni.net/a-propos/) – Website __[moodletoolguide.net](https://moodletoolguide.net)__ piblicado sob a licença [Creative Commons BY-NC-SA 4.0 International](https://creativecommons.org/licenses/by-nc-sa/4.0/).


      Baseado na ideia de [Joyce Seitzinger](https://twitter.com/catspyjamasnz) do [Eastern Institute of Technology](https://www.eit.ac.nz/) (NZ), adaptado por [Nicolas Martignoni](https://blog.martignoni.net/a-propos/), traduzido e adaptado para português por [Maria João](https://twitter.com/etutoria)."
    menu:
      main:
        - url: /
          name: Home
          weight: 1
        - url: /about/
          name: Sobre
          weight: 2
      icon:
        - url: 'https://github.com/martignoni/moodle-tool-guide'
          name: github
          weight: 2
